# -*- mode: shell-script; -*-
#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

path=(
      ${NODE_CONFIG_PREFIX}/bin
      ${CARGO_PREFIX:-${HOME}/.cargo}/bin
      $path
     )

export CUPS_SERVER=printserver0

# https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/
export TZ=:/etc/localtime

export PROJECT_HOME=${HOME}/workspace
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export WORKON_HOME=${HOME}/.virtualenvs
export NODE_CONFIG_PREFIX=${HOME}/.node-modules
export CARGO_PREFIX=${HOME}/.cargo
if (( $#commands[rust] )); then
    export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src
fi


