# -*- mode: shell-script; -*-
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias -s pdf=exo-open
alias -s html=browser
alias -s htm=browser
alias -s zip=file-roller
alias -s tar=file-roller
alias -s gz=file-roller
alias -s bz2=file-roller
alias -s rar=file-roller
alias -s mp4=mplayer
alias -s mov=mplayer
alias -s avi=mplayer
alias -s png=sxiv
alias -s jpg=sxiv
alias -s jpeg=sxiv
alias -s gif=sxiv
alias -s mp3=mpg123


alias -g L="| less"
alias -g EL="|& less"

# Customize to your needs...
[ -f "${HOME}/.zshrc.local" ] && source ${HOME}/.zshrc.local
[ -f '${WORKON_HOME}/default/bin/aws_zsh_completer.sh' ] && source '${WORKON_HOME}/default/bin/aws_zsh_completer.sh'

workon default

alias emacs="emacsclient -a '' -t"

nbsp=$'\u00a0'
bindkey $nbsp kill-whole-line

if [[ -S "/run/user/$(id -u)/gnupg/S.gpg-agent" ]] ; then
    export GPG_TTY=$(tty)
    echo "UPDATESTARTUPTTY" | gpg-connect-agent >& /dev/null
fi
